Document: fn-qtquick-env
Title: Debian fn-qtquick-env Manual
Author: <insert document author here>
Abstract: This manual describes what fn-qtquick-env is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fn-qtquick-env/fn-qtquick-env.sgml.gz

Format: postscript
Files: /usr/share/doc/fn-qtquick-env/fn-qtquick-env.ps.gz

Format: text
Files: /usr/share/doc/fn-qtquick-env/fn-qtquick-env.text.gz

Format: HTML
Index: /usr/share/doc/fn-qtquick-env/html/index.html
Files: /usr/share/doc/fn-qtquick-env/html/*.html
